### ISSUE TITLE
config/reporter.php doesn't seem to get picked up

### ISSUE THREAD

**Issue by FreekVR** [webmenedzser/craft-reporter#2]
Hi!

Thanks for the plugin. However, I am using project config, and the plugin seems to add the api key which I originally generated to the project config file, even though I've configured it to use a `config/reporter.php` config file like this:

.env
```
REPORTER_API_KEY=foobar
```

config/reporter.php
```
<?php

return [
    'apiKey' => env('REPORTER_API_KEY', '')
];
```

It seems to still add the defined API key to `project.yaml` no matter what I try, though:

config/project.yaml
```  
craft-reporter:
    edition: standard
    enabled: true
    schemaVersion: 1.1.0
    settings:
      apiKey: xxxxxxx (original generated api key)
```

Expected behaviour:

- api key is not set in project.yaml
- reporter uses api key as defined in the config file
- I cannot generate / submit / save a key in the admin CP as it should fetch it from the config file
